info:
component: Zuul Server

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000000

ribbon.ReadTimeout: 10000000
zuul.host.connect-timeout-millis: 10000000
zuul.host.socket-timeout-millis: 10000000

endpoints:
restart:
enabled: true
shutdown:
enabled: true
health:
sensitive: false

zuul:
routes:
gui:
path: /**
url: http://localhost:8080/
backend:
path: /api/**
url: http://localhost:8081/

logging:
level:
ROOT: INFO
org.springframework.web: INFO